### ISSUE TITLE
Empty AuthScheme not possible for headers

### ISSUE THREAD

**Issue by 418Coffee** [gofiber/jwt#118]
Hello,

I'm trying to do something similar to #103, extract a JWT from a custom header field.
```json
{
    "X-Auth": "eyJ....."
}
```

I believe currently, it's impossible to achieve this, because [an empty `AuthScheme` value gets interpreted as default and set to "Bearer"](https://github.com/gofiber/jwt/blob/4df911ba9c33b3d516c445ab192a8e668b6506d8/config.go#L159): 
```go
if cfg.AuthScheme == "" {
    cfg.AuthScheme = "Bearer"
}
```

Perhaps we can default `AuthScheme` to "Bearer" if `AuthScheme == "" && TokenLookup == defaultTokenLookup`. 
Please let me know what you think about this. I would be happy to make a PR.

**Comment by gaby** [comment]
@418Coffee Send a PR, as long as it's backwards compatible should be fine. :-)
