### ISSUE TITLE
Multimple Extractors

### ISSUE THREAD

**Issue by amaury-tobias** [gofiber/jwt#12]
Its possible to use multiple extractors by example from cookie and Header at the same time

**Comment by Fenny** [comment]
Hey @amaury-tobias, this is currently not possible. I think this is a unique use-case to seek multiple places for the JWT token.

**Comment by amaury-tobias** [comment]
I do this https://github.com/amaury-tobias/jwt i dont know if it's de best aproach, but work on my setup

**Comment by Fenny** [comment]
LGTM, I'm only missing a test case where this is tested. If you could add that we can merge it right away.

PS: Don't forget to trim the space after splitting the `TokenLookup`
```go
	extractors := make([]func(c *fiber.Ctx) (string, error), 0)
	rootParts := strings.Split(cfg.TokenLookup, ",")
	for _, rootPart := range rootParts {
		parts := strings.Split(strings.TrimSpace(rootPart), ":")
```
