### ISSUE TITLE
Update to support github.com/golang-jwt/jwt/v5

### ISSUE THREAD

**Issue by MicahParks** [gofiber/jwt#128]
The upstream JWT package, [`github.com/golang-jwt/jwt/4`](https://github.com/golang-jwt/jwt) has been updated to `/v5`. See [this release](https://github.com/golang-jwt/jwt/releases/tag/v5.0.0).

Perhaps now would be a good time to use [`github.com/MicahParks/keyfunc/v2`](https://github.com/MicahParks/keyfunc). Code from the `keyfunc` pre-release was added in [this pull request](https://github.com/gofiber/jwt/pull/57), but this project still holds bugs from that version. Using [`github.com/MicahParks/keyfunc/v2`](https://github.com/MicahParks/keyfunc) would also help resolve:
* https://github.com/gofiber/jwt/issues/73
* https://github.com/gofiber/jwt/issues/75

**Comment by ReneWerner87** [comment]
@MicahParks can you provide a PR

**Comment by MicahParks** [comment]
I've created https://github.com/gofiber/jwt/pull/129 with the intention to fulfill this issue.
