### ISSUE TITLE
how to handle optional auth route 

### ISSUE THREAD

**Issue by vipinblue** [gofiber/jwt#15]
I'm trying to use middleware as  optional  in unauthenticated routes 
And if user sending token then I can fetch claims 
if token not present in the header then I can abort

**Comment by yaliv** [comment]
I need that too. Namely, "validate the token if exist".
If you know about [express-jwt](https://github.com/auth0/express-jwt) (Node.js), there we can use optional validation by setting `credentialsRequired: false`.

**Comment by cyucelen** [comment]
You can create a new middleware with filter parameter.

```go
func OptinalProtected(signingKey string) func(c *fiber.Ctx) {
	return jwtMiddleware.New(jwtMiddleware.Config{
		SigningKey: []byte(signingKey),
		Filter: func(c *fiber.Ctx) bool {
			return c.Get("Authorization") == ""
		},
	})
}
```
