### ISSUE TITLE
Discuss naming

### ISSUE THREAD

**Issue by Fenny** [gofiber/jwt#2]
I currently added `jwtware "github.com/gofiber/jwt"` to avoid the name conflict with the official `jwt` package, this might be something that could be a little bit cleaner.

**Comment by raymayemir** [comment]
I think this is enough to understand that these are two different libraries. You can also specify in the description.

**Comment by Fenny** [comment]
@raymayemir [`v0.0.4`](https://github.com/gofiber/jwt/releases/tag/v0.0.4) uses `jwtware` as package name 👍
