### ISSUE TITLE
Get Claims data from JWT

### ISSUE THREAD

**Issue by maverickVision** [gofiber/jwt#23]
Hi, I need to get the user info from inside the Claims map from them JWT token. So far I got the contents of the Ctx.Local("user"), but when I try to access the Claims map, I get the following message: `Claims undefined (type interface {} is interface with no methods)`.
I'm still pretty new on Golang, so I tried to convert it to a map[int]string, but has got no success. Can anyone help me?

**Comment by maverickVision** [comment]
Just got it working.

```
user := c.Locals("user").(*jwt.Token)
claims := user.Claims.(jwt.MapClaims)
userID := claims["user_id"].(float64)
```

**Comment by LNMMusic** [comment]
its not working for me. There are 2 libraries to get JWT
- "github.com/dgrijalva/jwt-go"
- "github.com/golang-jwt/jwt/v4"

The last one completes the assertion but the first one fails. I don't kno why. They have the same content
