### ISSUE TITLE
How to implement refresh token

### ISSUE THREAD

**Issue by raveltan** [gofiber/jwt#24]

**Comment by raveltan** [comment]
```Go
app := fiber.New()
	app.Use(cors.New())

	//Unrestricted route
	app.Post("/api/login", Login)
	app.Post("/api/register", Register)

	//Refresh route
	app.Use(jwtware.New(jwtware.Config{
		SigningKey: []byte("GIAO GIAO"),
	}))

	app.Get("/api/refresh", Refresh)

	//Restricted route
	app.Use(jwtware.New(jwtware.Config{
		SigningKey: []byte("一给我里GIAO GIAO"),
	}))

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("hello")
	})
```
I tried to implement refresh token by using multiple instances of the jwtware with different signing key ,but it doesn't seems to work, is there any recomended way to implement refresh token?

**Comment by cybercoder** [comment]
@raveltan did you have any success in it?

**Comment by raveltan** [comment]
@cybercoder i implement it by creating a seperate middleware for routes that are using token and refresh token, so they have different secret for the jwt encryption, so the refresh token don't just end up as a regular token with longer life time. And refresh token can only be used on the route to generate new tokens

**Comment by cybercoder** [comment]
> @cybercoder i implement it by creating a seperate middleware for routes that are using token and refresh token, so they have different secret for the jwt encryption, so the refresh token don't just end up as a regular token with longer life time. And refresh token can only be used on the route to generate new tokens

ok so i need to write my middleware.
