### ISSUE TITLE
how to get username, user id from claims when working in handlers?

### ISSUE THREAD

**Issue by buffalus** [gofiber/jwt#27]
I use the following code to get username and user id in handler:

	user := c.Locals("user").(*jwt.Token)
	claims := user.Claims.(jwt.MapClaims)
	userID := claims["user_id"].(string)
        userName := claims["username"].(string)

But with error below: 
panic: interface conversion: interface {} is nil, not *jwt.Token

Can anyone fix it?

Thank you very much!

**Comment by buffalus** [comment]
Sorry, my mistake.
the codes works!

**Comment by Sharor** [comment]
I had the same issue, and had to look a while longer to figure out my mistake. If anyone comes here later with the same issue - 

My problem was that I was trying to resolve claims in a route that was "public", before the jwtware takes effect in main.go

It only worked after I tried to extract claims in a route after the SigningSecret 🙂
