### ISSUE TITLE
Request to release v0.0.3

### ISSUE THREAD

**Issue by 979156** [gofiber/jwt#3]
Hi Fenny,
Thank you for your well-organized library.
Could you please publish v0.0.3 little bit earlier with jwtware?
Importing fiber as ".././fiber" disables jwt build using mod.
Sorry if I am disturbing you with tiny stuff, but this has possibility to make many newcomers like me retreat.
'jwtware' looks also good to me.

**Comment by Fenny** [comment]
@979156 [`v0.0.4`](https://github.com/gofiber/jwt/releases/tag/v0.0.4) fixed the import and package name `jwtware`

**Comment by 979156** [comment]
@Fenny thanks a lot

**Comment by Fenny** [comment]
@979156 feel free to join us on Telegram if you have further questions! https://t.me/gofiber

**Comment by 979156** [comment]
@Fenny Sure! Thanks!
