### ISSUE TITLE
How is expiration handled?

### ISSUE THREAD

**Issue by jj0e** [gofiber/jwt#49]
Hi, I have a quick question regarding `exp` claim in a token. I see in the example that you add it on a token creation, however I'm having trouble finding how it's handled. Is it automatically handled? Or do I need to insert some sort of function that checks it?

**Comment by ReneWerner87** [comment]
https://github.com/golang-jwt/jwt/blob/c018921cb3d35cbdff377f2985970143ffc02cef/map_claims.go#L36-L44

if you use the mapClaim and set the exp, it will be traded automatically
https://tools.ietf.org/html/rfc7519#section-4.1

**Comment by jj0e** [comment]
That's exactly what I was looking for! Thank you 👍🏻
