### ISSUE TITLE
 Request to release v0.0.6

### ISSUE THREAD

**Issue by eu-g-en** [gofiber/jwt#5]
Hi Fenny,
Thank you for your excellent library.
I currently added jwtware as package name in `main_test.go` to avoid this error message: `found packages jwtware (main.go) and jwt (main_test.go)`.
Sorry if I am disturbing you with tiny stuff, but this has possibility to make many newcomers like me retreat.

**Comment by thomasvvugt** [comment]
Hi @eu-g-en and thanks for creating this issue!
We merged a fix in #6

**Comment by eu-g-en** [comment]
@thomasvvugt thanks so much for the nice work)
