### ISSUE TITLE
How to control the format which a value is parsed during foo.Claims.(jwt.MapClaims)?

### ISSUE THREAD

**Issue by phtdacosta** [gofiber/jwt#8]
I took the following example as a guide,
`user := c.Locals("user").(*jwt.Token)`
`claims := user.Claims.(jwt.MapClaims)`
`name := claims["name"].(string)`

 but unlike the example, the key I am looking for is not string, but int64 (It is an integer: 1, 2, 3). Unfortunately, I get the following error if I keep the *.(string)*
`cannot convert claims["bar"] (type interface {}) to type string: need type assertion`
and the following error, if I replace the *.(string)* for *.(int64)*
`panic: interface conversion: interface {} is float64, not string`

So, how can I get my number as int64 instead of string or this float64 (??) that it is guessing to be?

**Comment by Fenny** [comment]
@phtdacosta this seems more like a Go question, maybe this topic helps you out https://stackoverflow.com/questions/20767724/converting-unknown-interface-to-float64-in-golang

**Comment by koddr** [comment]
@phtdacosta hi! 👋 

For example, I make this on my _production_ code to check UUID (using [google/uuid](https://github.com/google/uuid)) from JWT:

```go
// UpdateUserProfile update user profile by ID or 500 error
// (works only for profile's owner or website admin)
func UpdateUserProfile(c *fiber.Ctx) {
	// Get data from JWT
 	token := c.Locals("user").(*jwt.Token)
	claims := token.Claims.(jwt.MapClaims)

	// Check admin status
	isAdmin := claims["is_admin"].(bool)

	// Check UUID from current user
	currentUserID, errParse := uuid.Parse(claims["id"].(string))
	if errParse != nil {
		c.Status(500).JSON(fiber.Map{"error": true, "msg": errParse.Error()})
		return
	}

        // ...
```

Try similar way, please 😉
